In [ ]:
import numpy as np
from PIL import Image
import numpy as np
import matplotlib.image as image
import cv2
import os
from os import listdir
from numpy import asarray
import seaborn as sns
import patoolib


In [ ]:
import numpy as np
from PIL import Image
import numpy as np
import cv2
import os
from os import listdir
from numpy import asarray
np.set_printoptions(threshold=np.inf)
import seaborn as sns
import patoolib


In [ ]:
!pip install patool

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
patoolib.extract_archive('/content/Data.zip')

patool: Extracting /content/Data.zip ...
patool: running /usr/bin/7z x -o./Unpack_vqv1dlwn -- /content/Data.zip
patool: ... /content/Data.zip extracted to `Data1' (local file exists).


'Data1'

In [ ]:
X = []
for i in range(1,2401):
    img= image.imread(f'/content/Data/Train/{i}.jpg')
    X.append(img.flatten())

X = np.array(X)

In [ ]:
c0=[]
notc0=[]
c1=[]
notc1=[]
c2=[]
notc2=[]
c3=[]
notc3=[]
c4=[]
notc4=[]
c5=[]
notc5=[]
c6=[]
notc6=[]
c7=[]
notc7=[]
c8=[]
notc8=[]
c9=[]
notc9=[]

In [ ]:
for i in range(2400):
    if(i<240):
      c0.append(X[i])
    else :
     notc0.append(X[i])
    if (240<=i<480):
      c1.append(X[i])
    else:
     notc1.append(X[i])
    if(480<=i<720):
      c2.append(X[i])
    else:
      notc2.append(X[i])
    if(720<=i<960):
      c3.append(X[i])
    else:
      notc3.append(X[i])
    if(960<=i<1200):
      c4.append(X[i])
    else:
      notc4.append(X[i])
    if(1200<=i<1440):
      c5.append(X[i])
    else:
      notc5.append(X[i])
    if(1440<=i<1680):
      c6.append(X[i])
    else:
      notc6.append(X[i])
    if(1680<=i<1920):
      c7.append(X[i])
    else:
      notc7.append(X[i])
    if(1920<=i<2160):
      c8.append(X[i])
    else:
      notc8.append(X[i])
    if(2160<=i<2400):
      c9.append(X[i])
    else:
      notc9.append(X[i])

In [ ]:
notc0 = np.array(notc0)
notc1 = np.array(notc1)
notc2 = np.array(notc2)
notc3 = np.array(notc3)
notc4 = np.array(notc4)
notc5 = np.array(notc5)
notc6 = np.array(notc6)
notc7 = np.array(notc7)
notc8 = np.array(notc8)
notc9 = np.array(notc9)
c0 = np.array(c0)
c1 = np.array(c1)
c2 = np.array(c2)
c3 = np.array(c3)
c4 = np.array(c4)
c5 = np.array(c5)
c6 = np.array(c6)
c7 = np.array(c7)
c8 = np.array(c8)
c9 = np.array(c9)

In [ ]:
classes=[c0,c1,c2,c3,c4,c5,c6,c7,c8,c9]
notclasses=[notc0,notc1,notc2,notc3,notc4,notc5,notc6,notc7,notc8,notc9]

In [ ]:
mean0=np.sum(notc0,axis=0)/len(notc0)
mean1=np.sum(notc1,axis=0)/len(notc1)
mean2=np.sum(notc2,axis=0)/len(notc2)
mean3=np.sum(notc3,axis=0)/len(notc3)
mean4=np.sum(notc4,axis=0)/len(notc4)
mean5=np.sum(notc5,axis=0)/len(notc5)
mean6=np.sum(notc6,axis=0)/len(notc6)
mean7=np.sum(notc7,axis=0)/len(notc7)
mean8=np.sum(notc8,axis=0)/len(notc8)
mean9=np.sum(notc9,axis=0)/len(notc9)

meanc0=np.sum(c0,axis=0)/len(c0)
meanc1=np.sum(c1,axis=0)/len(c1)
meanc2=np.sum(c2,axis=0)/len(c2)
meanc3=np.sum(c3,axis=0)/len(c3)
meanc4=np.sum(c4,axis=0)/len(c4)
meanc5=np.sum(c5,axis=0)/len(c5)
meanc6=np.sum(c6,axis=0)/len(c6)
meanc7=np.sum(c7,axis=0)/len(c7)
meanc8=np.sum(c8,axis=0)/len(c8)
meanc9=np.sum(c9,axis=0)/len(c9)

In [ ]:
means1=[mean0,mean1,mean2,mean3,mean4,mean5,mean6,mean7,mean8,mean9]#deosnt belong
means2=[meanc0,meanc1,meanc2,meanc3,meanc4,meanc5,meanc6,meanc7,meanc8,meanc9]#belongs

In [ ]:
SWj1=[]
for i in range(10):
  sum=np.zeros((784,784))
  for j in range(240):
    x1= (classes[i][j]-means2[i]).reshape(784,1)
    xtrans1=x1.reshape(1,784)
    xxt1=x1.dot(xtrans1)
    sum=sum+xxt1

  SWj1.append(sum)

In [ ]:
SWj2=[]
for i in range(10):
  sum=np.zeros((784,784))
  for j in range(2160):
    x1= (notclasses[i][j]-means1[i]).reshape(784,1)
    xtrans1=x1.reshape(1,784)
    xxt1=x1.dot(xtrans1)
    sum=sum+xxt1

  SWj2.append(sum)


In [ ]:
SW=[]
for i in range(10):
 sw=SWj1[i]+SWj2[i]
 SW.append(sw)

10

In [ ]:
SWINV=[]
for i in range(10):
 inverse=np.linalg.pinv(SW[i])
 SWINV.append(inverse)

In [ ]:
weights=[]
for i in range(10):
  w=(means1[i]-means2[i]).dot(SWINV[i])
  weights.append(w)



In [ ]:
len(weights)

10

In [ ]:
Test = []
for i in range(1,201):
    img= image.imread(f'/content/Data/Test/{i}.jpg')
    Test.append(img.flatten())

Test = np.array(Test)

In [ ]:
result=np.ones([200])
for i in range(200):
  image=Test[i]
  tests=np.zeros([10])
  for j in range(10):
   currw=weights[j]
   tests[j]=image.dot(currw)
  min=np.argmin(tests)
  result[i]= min



In [ ]:
Test[0]

In [ ]:
labels = np.genfromtxt("./Data/Test/Test Labels.txt")
labels

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
       7., 7., 7., 7., 7., 7., 7., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
       8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 9., 9., 9., 9., 9., 9., 9.,
       9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9.])

In [ ]:
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

from sklearn.metrics import accuracy_score
from sklearn import metrics


In [ ]:
confusionmat = metrics.confusion_matrix(labels,result)
plt.savefig('./ConfusionNoBias.jpg')
acc = metrics.accuracy_score(labels,result)
display(confusionmat,acc)
####


array([[19,  0,  0,  0,  0,  0,  1,  0,  0,  0],
       [ 0, 20,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2, 12,  2,  2,  1,  0,  0,  1,  0],
       [ 0,  0,  0, 18,  0,  0,  0,  0,  2,  0],
       [ 0,  0,  0,  1, 10,  1,  3,  0,  3,  2],
       [ 0,  0,  0,  2,  0, 11,  1,  0,  4,  2],
       [ 0,  0,  0,  0,  0,  0, 20,  0,  0,  0],
       [ 0,  0,  1,  1,  0,  0,  0, 16,  0,  2],
       [ 0,  0,  0,  1,  0,  1,  0,  0, 18,  0],
       [ 1,  0,  0,  3,  1,  0,  0,  5,  0, 10]])

0.77

<Figure size 432x288 with 0 Axes>

In [ ]:
weights[0].shape

(784,)

In [ ]:
weights2=[]
for i in range(10):
  x=np.multiply(weights[i].reshape(1,784),-1)
  y=(means2[i]+means1[i])/2
  w=x.dot(y)
  weights2.append(w)







In [ ]:
weights2

[array([0.00619621]),
 array([0.00273676]),
 array([0.00678718]),
 array([0.00703005]),
 array([0.00288468]),
 array([0.0031758]),
 array([0.00848218]),
 array([0.0060023]),
 array([0.00699402]),
 array([0.00354216])]